work_id: yuexia
name: 月下 - 崩坏三舰长线 - 第一节
dialog_box:
  x: 0.14
  y: 0.815
  w: 0.7
  h: 0.125
name_box:
  x: 0.1398
  y: 0.7308
  w: 0.7031
  h: 0.0778
dialog_preprocess: game_dialogue
name_preprocess: game_namebox
ocr_engine: paddleocr
target_fps: 2.0
review_threshold: 0.7
speaker_aliases:
  舰长: []
  姬子:
  - 姬子老师
  琪亚娜:
  - 琪亚
  芽衣: []
  布洛妮娅:
  - 布洛妮
  德丽莎: []
  符华: []
  旁白: []
  系统: []
